name: PR help
# cSpell:ignore otelbot

on:
  issue_comment:
    types: [created]
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'PR number to comment on'
        required: true
        type: number

permissions:
  contents: read

env:
  COMMENT: ${{ github.event.comment.body }}
  PR_NUM: ${{ github.event.inputs.pr_number || github.event.issue.number }}

jobs:
  show-help:
    name: Show PR actions help
    runs-on: ubuntu-latest
    if: |
      github.event.issue.pull_request &&
      github.event.comment.body == '/help'

    permissions:
      pull-requests: write

    steps:
      - uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - uses: actions/checkout@v5
        with:
          fetch-depth: 1

      - uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc

      - uses: actions/create-github-app-token@67018539274d69449ef7c02e8e71183d1719ab42 # v2.1.4
        id: otelbot-token
        with:
          app-id: ${{ vars.OTELBOT_APP_ID }}
          private-key: ${{ secrets.OTELBOT_PRIVATE_KEY }}

      - name: Generate help text
        id: help
        run: |
          # Generate help text and save to file
          node scripts/generate-pr-help.js > help.txt

          # Read the help text and set as output
          # Using heredoc to handle multiline content safely
          {
            echo 'helptext<<EOF'
            cat help.txt
            echo EOF
          } >> "$GITHUB_OUTPUT"

      - name: Post help comment
        run: |
          gh pr comment $PR_NUM --body "${{ steps.help.outputs.helptext }}"
        env:
          GH_TOKEN: ${{ steps.otelbot-token.outputs.token }}

      - name: Add reaction to trigger comment
        run: |
          # Add a 👀 reaction to acknowledge the command
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${{ github.repository }}/issues/comments/${{ github.event.comment.id }}/reactions \
            -f content='eyes'
        env:
          GH_TOKEN: ${{ steps.otelbot-token.outputs.token }}
